AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ECS Cluster for the Momenton Challenge
  
Parameters:
  VpcStack:
    Type: String
    Description: The name of the VPC Stack which provides network services to this ECS cluster
    
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    
  ECSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role'
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM'
      Path: '/'
      Policies:
        -
          PolicyName: 'AWSServiceAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action: 'cloudwatch:PutMetricData'
                Resource: '*'
        -
          PolicyName: 'AllowTaskLogs'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  ECSInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref ECSRole
        
  GatewaySecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${VpcStack}-VpcId'
      GroupDescription: Enable HTTP from the public internet
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIp: 0.0.0.0/0
          
  ECSSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${VpcStack}-VpcId'
      GroupDescription: Enable access to Containers in the ECS Cluster
      SecurityGroupIngress:
        - Description: Allow access to containers from the Internet Load balancer
          IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref GatewaySecGroup
        - Description: Allow access to containers from the Internal Load balancer
          IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 
            Fn::ImportValue: !Sub '${VpcStack}-VpcCidr'
          
  ECSLaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      IamInstanceProfile: !Ref ECSInstanceProfile
      # this image id obtained from querying ssm parameter: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended
      # in ap-southeast-2
      ImageId: ami-039bb4c3a7946ce19
      InstanceType: t3.micro
      AssociatePublicIpAddress: false
      SecurityGroups:
        - !Ref ECSSecGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
            |
            #cloud-config:
            package_upgrade: true
            packages:
              - amazon-ssm-agent
            runcmd:
              - [systemctl, enable, amazon-ssm-agent]
              - [systemctl, start, amazon-ssm-agent]
              - echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
                
  ECSGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub '${VpcStack}-Private0'
        - Fn::ImportValue: !Sub '${VpcStack}-Private1'
      MetricsCollection:
        -
          Granularity: 1Minute
      HealthCheckType: EC2
      HealthCheckGracePeriod: '60'
      Cooldown: '30'
      LaunchConfigurationName: !Ref ECSLaunchConfig
      MinSize: 0
      MaxSize: 1
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ECSGroup'
          PropagateAtLaunch: 'true'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        WaitOnResourceSignals: 'false'
        PauseTime: PT1M00S

Outputs:
  ECSClusterArn:
    Description: The ARN of this ECS Cluster
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECSClusterArn'
      
  ECSGroup:
    Description: >-
      The AutoScaling group which controls the Container instances in the ECS Cluser
    Value: !Ref ECSGroup

  ECSSecGroup:
    Description: The Security group which controls access to the ECS Cluster
    Value: !Ref ECSSecGroup
    Export:
      Name: !Sub '${AWS::StackName}-ECSSecGroup'
      
  GatewaySecGroup:
    Description: The Security group which controls access to the Gateway
    Value: !Ref GatewaySecGroup
    Export:
      Name: !Sub '${AWS::StackName}-GatewaySecGroup'